version: "3.8"

services:
  business-layer:
    build: ./business-layer
    container_name: notification-generator-api
    ports:
      - 3000:3000
    volumes:
      - ./business-layer/src:/app/src
  presentation-layer:
    build: ./presentation-layer
    container_name: notification-generator-app
    ports:
      - 8080:5173
    volumes:
      - ./presentation-layer/src:/app/src
